# Auto-generated by GET /api/admin/image-index/export
# DO NOT EDIT MANUALLY — re-generate when aac_images changes or mascots are added.
#
# Stores GCS-relative paths (no bucket prefix).  The server prepends:
#   https://storage.googleapis.com/{AAC_IMAGES_BUCKET_NAME}/
# so this file works identically in dev, test, and prod.
#
# To regenerate:
#   1. POST /api/admin/image-index/build       (builds Firestore index)
#   2. GET  /api/admin/image-index/export      (copy response body)
#   3. Paste here and commit

from typing import Dict

STATIC_IMAGE_ASSIGNMENTS: Dict[str, Dict[str, str]] = {}
